spring:
  ai:
    mcp:
      client:
        enabled: true
        name: mcp-client-demo
        version: 1.0.0
        request-timeout: 30s
        type: SYNC  # or ASYNC for reactive applications
        stdio:
          root-change-notification: false
          connections:
            server1:
              command: /usr/bin/java
              args:
                - -jar
                - ../mcp-server-demo/target/mcp-server-demo-0.0.1-SNAPSHOT.jar
          #servers-configuration: classpath:/mcp-servers-config.json

    openai:
      api-key: ${SPRING_OPEN_AI_KEY}

server:
  port: 8090