spring:
  ai:
    mcp:
      client:
        enabled: true
        name: mcp-client-demo
        version: 1.0.0
        request-timeout: 30s
        type: SYNC  # or ASYNC for reactive applications
        sse:
          connections:
            server1:
              url: http://localhost:8080

    openai:
      api-key: ${SPRING_OPEN_AI_KEY}

server:
  port: 8090